// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gdalservice.proto

/*
Package gdalservice is a generated protocol buffer package.

It is generated from these files:
gdalservice.proto

It has these top-level messages:
GeoRequest
Overview
GeoMetaData
GeoFile
GeoFileAndError
*/
package gdalservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GeoRequest struct {
	FilePath string `protobuf:"bytes,1,opt,name=filePath" json:"filePath,omitempty"`
}

func (m *GeoRequest) Reset()                    { *m = GeoRequest{} }
func (m *GeoRequest) String() string            { return proto.CompactTextString(m) }
func (*GeoRequest) ProtoMessage()               {}
func (*GeoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GeoRequest) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

type Overview struct {
	XSize int32 `protobuf:"varint,1,opt,name=xSize" json:"xSize,omitempty"`
	YSize int32 `protobuf:"varint,2,opt,name=ySize" json:"ySize,omitempty"`
}

func (m *Overview) Reset()                    { *m = Overview{} }
func (m *Overview) String() string            { return proto.CompactTextString(m) }
func (*Overview) ProtoMessage()               {}
func (*Overview) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Overview) GetXSize() int32 {
	if m != nil {
		return m.XSize
	}
	return 0
}

func (m *Overview) GetYSize() int32 {
	if m != nil {
		return m.YSize
	}
	return 0
}

type GeoMetaData struct {
	DatasetName  string                       `protobuf:"bytes,1,opt,name=datasetName" json:"datasetName,omitempty"`
	NameSpace    string                       `protobuf:"bytes,2,opt,name=nameSpace" json:"nameSpace,omitempty"`
	Type         string                       `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	RasterCount  int32                        `protobuf:"varint,4,opt,name=rasterCount" json:"rasterCount,omitempty"`
	TimeStamps   []*google_protobuf.Timestamp `protobuf:"bytes,5,rep,name=timeStamps" json:"timeStamps,omitempty"`
	Overviews    []*Overview                  `protobuf:"bytes,6,rep,name=overviews" json:"overviews,omitempty"`
	XSize        int32                        `protobuf:"varint,7,opt,name=xSize" json:"xSize,omitempty"`
	YSize        int32                        `protobuf:"varint,8,opt,name=ySize" json:"ySize,omitempty"`
	GeoTransform []float64                    `protobuf:"fixed64,9,rep,packed,name=geoTransform" json:"geoTransform,omitempty"`
	Polygon      string                       `protobuf:"bytes,10,opt,name=polygon" json:"polygon,omitempty"`
	ProjWKT      string                       `protobuf:"bytes,11,opt,name=projWKT" json:"projWKT,omitempty"`
	Proj4        string                       `protobuf:"bytes,12,opt,name=proj4" json:"proj4,omitempty"`
}

func (m *GeoMetaData) Reset()                    { *m = GeoMetaData{} }
func (m *GeoMetaData) String() string            { return proto.CompactTextString(m) }
func (*GeoMetaData) ProtoMessage()               {}
func (*GeoMetaData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GeoMetaData) GetDatasetName() string {
	if m != nil {
		return m.DatasetName
	}
	return ""
}

func (m *GeoMetaData) GetNameSpace() string {
	if m != nil {
		return m.NameSpace
	}
	return ""
}

func (m *GeoMetaData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GeoMetaData) GetRasterCount() int32 {
	if m != nil {
		return m.RasterCount
	}
	return 0
}

func (m *GeoMetaData) GetTimeStamps() []*google_protobuf.Timestamp {
	if m != nil {
		return m.TimeStamps
	}
	return nil
}

func (m *GeoMetaData) GetOverviews() []*Overview {
	if m != nil {
		return m.Overviews
	}
	return nil
}

func (m *GeoMetaData) GetXSize() int32 {
	if m != nil {
		return m.XSize
	}
	return 0
}

func (m *GeoMetaData) GetYSize() int32 {
	if m != nil {
		return m.YSize
	}
	return 0
}

func (m *GeoMetaData) GetGeoTransform() []float64 {
	if m != nil {
		return m.GeoTransform
	}
	return nil
}

func (m *GeoMetaData) GetPolygon() string {
	if m != nil {
		return m.Polygon
	}
	return ""
}

func (m *GeoMetaData) GetProjWKT() string {
	if m != nil {
		return m.ProjWKT
	}
	return ""
}

func (m *GeoMetaData) GetProj4() string {
	if m != nil {
		return m.Proj4
	}
	return ""
}

type GeoFile struct {
	FileName string         `protobuf:"bytes,1,opt,name=fileName" json:"fileName,omitempty"`
	Driver   string         `protobuf:"bytes,2,opt,name=driver" json:"driver,omitempty"`
	DataSets []*GeoMetaData `protobuf:"bytes,3,rep,name=dataSets" json:"dataSets,omitempty"`
}

func (m *GeoFile) Reset()                    { *m = GeoFile{} }
func (m *GeoFile) String() string            { return proto.CompactTextString(m) }
func (*GeoFile) ProtoMessage()               {}
func (*GeoFile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GeoFile) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *GeoFile) GetDriver() string {
	if m != nil {
		return m.Driver
	}
	return ""
}

func (m *GeoFile) GetDataSets() []*GeoMetaData {
	if m != nil {
		return m.DataSets
	}
	return nil
}

type GeoFileAndError struct {
	GeoFile *GeoFile `protobuf:"bytes,1,opt,name=geoFile" json:"geoFile,omitempty"`
	Error   string   `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *GeoFileAndError) Reset()                    { *m = GeoFileAndError{} }
func (m *GeoFileAndError) String() string            { return proto.CompactTextString(m) }
func (*GeoFileAndError) ProtoMessage()               {}
func (*GeoFileAndError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GeoFileAndError) GetGeoFile() *GeoFile {
	if m != nil {
		return m.GeoFile
	}
	return nil
}

func (m *GeoFileAndError) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*GeoRequest)(nil), "gdalservice.GeoRequest")
	proto.RegisterType((*Overview)(nil), "gdalservice.Overview")
	proto.RegisterType((*GeoMetaData)(nil), "gdalservice.GeoMetaData")
	proto.RegisterType((*GeoFile)(nil), "gdalservice.GeoFile")
	proto.RegisterType((*GeoFileAndError)(nil), "gdalservice.GeoFileAndError")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GDAL service

type GDALClient interface {
	Info(ctx context.Context, in *GeoRequest, opts ...grpc.CallOption) (*GeoFile, error)
}

type gDALClient struct {
	cc *grpc.ClientConn
}

func NewGDALClient(cc *grpc.ClientConn) GDALClient {
	return &gDALClient{cc}
}

func (c *gDALClient) Info(ctx context.Context, in *GeoRequest, opts ...grpc.CallOption) (*GeoFile, error) {
	out := new(GeoFile)
	err := grpc.Invoke(ctx, "/gdalservice.GDAL/Info", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GDAL service

type GDALServer interface {
	Info(context.Context, *GeoRequest) (*GeoFile, error)
}

func RegisterGDALServer(s *grpc.Server, srv GDALServer) {
	s.RegisterService(&_GDAL_serviceDesc, srv)
}

func _GDAL_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GDALServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gdalservice.GDAL/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GDALServer).Info(ctx, req.(*GeoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GDAL_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gdalservice.GDAL",
	HandlerType: (*GDALServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _GDAL_Info_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gdalservice.proto",
}

func init() { proto.RegisterFile("gdalservice.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 446 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x55, 0x70, 0xbe, 0x3c, 0xae, 0x40, 0x5a, 0x15, 0x58, 0x45, 0x48, 0x44, 0x3e, 0xe5, 0xe4,
	0x4a, 0x69, 0xe1, 0x80, 0xc4, 0xa1, 0xa2, 0x10, 0x21, 0x3e, 0xb5, 0x89, 0xd4, 0xf3, 0xb6, 0x1e,
	0x1b, 0x23, 0xdb, 0x63, 0x76, 0x37, 0x81, 0xf0, 0x23, 0xf8, 0xcd, 0x68, 0x77, 0xed, 0xc4, 0xad,
	0x7a, 0xf3, 0x7b, 0xf3, 0xf6, 0x4d, 0xe6, 0xbd, 0xc0, 0xe3, 0x3c, 0x95, 0x65, 0x51, 0x67, 0x94,
	0x34, 0x8a, 0x0c, 0xb1, 0xc8, 0x62, 0x8d, 0x6a, 0x57, 0xdc, 0xe2, 0xec, 0x65, 0x4e, 0x94, 0x97,
	0x78, 0xe6, 0x46, 0x37, 0xdb, 0xec, 0xcc, 0x14, 0x15, 0x6a, 0x23, 0xab, 0xc6, 0xab, 0xe3, 0x05,
	0xc0, 0x0a, 0x49, 0xe0, 0xaf, 0x2d, 0x6a, 0xc3, 0x66, 0x30, 0xcd, 0x8a, 0x12, 0xbf, 0x4b, 0xf3,
	0x83, 0x0f, 0xe6, 0x83, 0x45, 0x28, 0x0e, 0x38, 0x7e, 0x0d, 0xd3, 0x6f, 0x3b, 0x6b, 0x8b, 0xbf,
	0xd9, 0x29, 0x8c, 0xfe, 0xac, 0x8b, 0xbf, 0xe8, 0x44, 0x23, 0xe1, 0x81, 0x65, 0xf7, 0x8e, 0x7d,
	0xe4, 0x59, 0x07, 0xe2, 0x7f, 0x01, 0x44, 0x2b, 0xa4, 0x2f, 0x68, 0xe4, 0x95, 0x34, 0x92, 0xcd,
	0x21, 0x4a, 0xa5, 0x91, 0x1a, 0xcd, 0x57, 0x59, 0x61, 0xbb, 0xa6, 0x4f, 0xb1, 0x17, 0x10, 0xd6,
	0xb2, 0xc2, 0x75, 0x23, 0x6f, 0xbd, 0x57, 0x28, 0x8e, 0x04, 0x63, 0x30, 0x34, 0xfb, 0x06, 0x79,
	0xe0, 0x06, 0xee, 0xdb, 0x7a, 0x2a, 0xa9, 0x0d, 0xaa, 0x77, 0xb4, 0xad, 0x0d, 0x1f, 0xba, 0xfd,
	0x7d, 0x8a, 0xbd, 0x01, 0xb0, 0xa7, 0xaf, 0xed, 0xe9, 0x9a, 0x8f, 0xe6, 0xc1, 0x22, 0x5a, 0xce,
	0x12, 0x9f, 0x4e, 0xd2, 0xa5, 0x93, 0x6c, 0xba, 0x74, 0x44, 0x4f, 0xcd, 0xce, 0x21, 0xa4, 0xf6,
	0x72, 0xcd, 0xc7, 0xee, 0xe9, 0xd3, 0xa4, 0x97, 0x72, 0xd2, 0xe5, 0x22, 0x8e, 0xba, 0x63, 0x44,
	0x93, 0x07, 0x23, 0x9a, 0xf6, 0x22, 0x62, 0x31, 0x9c, 0xe4, 0x48, 0x1b, 0x25, 0x6b, 0x9d, 0x91,
	0xaa, 0x78, 0x38, 0x0f, 0x16, 0x03, 0x71, 0x87, 0x63, 0x1c, 0x26, 0x0d, 0x95, 0xfb, 0x9c, 0x6a,
	0x0e, 0xee, 0xf2, 0x0e, 0xba, 0x89, 0xa2, 0x9f, 0xd7, 0x9f, 0x36, 0x3c, 0x6a, 0x27, 0x1e, 0xda,
	0x6d, 0xf6, 0xf3, 0x82, 0x9f, 0x38, 0xde, 0x83, 0x58, 0xc3, 0x64, 0x85, 0xf4, 0xa1, 0x28, 0xb1,
	0xeb, 0xbb, 0x57, 0xc4, 0x01, 0xb3, 0x67, 0x30, 0x4e, 0x55, 0xb1, 0x43, 0xd5, 0x56, 0xd0, 0x22,
	0x76, 0x01, 0x53, 0x5b, 0xd6, 0x1a, 0x8d, 0xe6, 0x81, 0x0b, 0x83, 0xdf, 0x09, 0xa3, 0xd7, 0xb5,
	0x38, 0x28, 0xe3, 0x6b, 0x78, 0xd2, 0x2e, 0xbd, 0xac, 0xd3, 0xf7, 0x4a, 0x91, 0x62, 0x09, 0x4c,
	0x72, 0x4f, 0xb9, 0xdd, 0xd1, 0xf2, 0xf4, 0xbe, 0x8f, 0x9d, 0x89, 0x4e, 0x64, 0xaf, 0x41, 0xfb,
	0xb0, 0xfd, 0x3d, 0x1e, 0x2c, 0xdf, 0xc2, 0x70, 0x75, 0x75, 0xf9, 0x99, 0xbd, 0x82, 0xe1, 0xc7,
	0x3a, 0x23, 0xf6, 0xfc, 0xbe, 0x49, 0xfb, 0xdf, 0x9e, 0x3d, 0xe8, 0x7e, 0x33, 0x76, 0xdd, 0x9f,
	0xff, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x68, 0xe7, 0x04, 0x46, 0x03, 0x00, 0x00,
}
